-- MySQL Script generated by MySQL Workbench
-- Sat Dec 11 00:22:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS PayrollManagementSystemDB;
CREATE DATABASE IF NOT EXISTS PayrollManagementSystemDB;
USE PayrollManagementSystemDB;
-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(256) NULL,
  `created` DATE NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Device`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Device` ;

CREATE TABLE IF NOT EXISTS `Device` (
  `device_id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NULL,
  `device_name` VARCHAR(100) NULL,
  `device_type` VARCHAR(100) NULL,
  PRIMARY KEY (`device_id`),
  INDEX `LOGS_IN_ACCOUNT_FK_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `LOGS_IN_ACCOUNT_FK`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`user_id`),
  INDEX `USER_ACCOUNT_FK_idx` (`account_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `CREATED_ACCOUNT_FK`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Session` ;

CREATE TABLE IF NOT EXISTS `Session` (
  `session_id` INT NOT NULL AUTO_INCREMENT,
  `device_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `start_time` TIMESTAMP(1) NULL,
  PRIMARY KEY (`session_id`, `device_id`, `user_id`),
  INDEX `SESSION_USER_FK_idx` (`user_id` ASC) VISIBLE,
  INDEX `SESSION_DEVICE_FK_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `SESSION_USER_PK_FK`
    FOREIGN KEY (`user_id`)
    REFERENCES `User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SESSION_DEVICE_PK_FK`
    FOREIGN KEY (`device_id`)
    REFERENCES `Device` (`device_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Company` ;

CREATE TABLE IF NOT EXISTS `Company` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `type` VARCHAR(255) NULL,
  PRIMARY KEY (`company_id`),
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  CONSTRAINT `COMPANY_ACCOUNT_FK`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payment Method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payment Method` ;

CREATE TABLE IF NOT EXISTS `Payment Method` (
  `pay_method_id` INT NOT NULL AUTO_INCREMENT,
  `isa_type` VARCHAR(45) NOT NULL,
  `description` VARCHAR(2048) NULL,
  PRIMARY KEY (`pay_method_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Company Supported Payment Methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Company Supported Payment Methods` ;

CREATE TABLE IF NOT EXISTS `Company Supported Payment Methods` (
  `comp_pay_methods_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `pay_method_id` INT NOT NULL,
  PRIMARY KEY (`comp_pay_methods_id`),
  INDEX `COMPANY_SUPPORTED_PAYMENT_METHODS_FK_idx` (`company_id` ASC) VISIBLE,
  INDEX `PAYMENT_METHODS_FOR_COMPANY_FK_idx` (`pay_method_id` ASC) VISIBLE,
  CONSTRAINT `COMPANYS_CHOSEN_PAYMENT_METHODS_PK_FK`
    FOREIGN KEY (`company_id`)
    REFERENCES `Company` (`company_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PAYMENT_METHODS_FOR_COMPANY_PK_FK`
    FOREIGN KEY (`pay_method_id`)
    REFERENCES `Payment Method` (`pay_method_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Person` ;

CREATE TABLE IF NOT EXISTS `Person` (
  `ssn` CHAR(9) NOT NULL,
  `isa_type` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`ssn`),
  UNIQUE INDEX `ssn_UNIQUE` (`ssn` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee` ;

CREATE TABLE IF NOT EXISTS `Employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `ssn` CHAR(9) NOT NULL,
  `isa_type` VARCHAR(45) NOT NULL,
  `start_work_date` DATE NOT NULL,
  `vacation_days` TINYINT(1) NOT NULL,
  `sick_days` TINYINT(1) NOT NULL,
  PRIMARY KEY (`employee_id`, `ssn`),
  CONSTRAINT `EMPLOYEE_PERSON_PK_FK`
    FOREIGN KEY (`ssn`)
    REFERENCES `Person` (`ssn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Company Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Company Employees` ;

CREATE TABLE IF NOT EXISTS `Company Employees` (
  `comp_emp_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`comp_emp_id`, `company_id`, `employee_id`),
  INDEX `COMPANY_WITH_EMPLOYEES_FK_idx` (`company_id` ASC) VISIBLE,
  INDEX `EMPLOYEES_AT_COMPANY_FK_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `COMPANY_WITH_EMPLOYEES_PK_FK`
    FOREIGN KEY (`company_id`)
    REFERENCES `Company` (`company_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `EMPLOYEES_AT_COMPANY_PK_FK`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Benefit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Benefit` ;

CREATE TABLE IF NOT EXISTS `Benefit` (
  `benefit_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(100) NOT NULL,
  `description` VARCHAR(4096) NULL,
  `cost` DECIMAL(65,2) NOT NULL,
  PRIMARY KEY (`benefit_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Company Offered Benefits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Company Offered Benefits` ;

CREATE TABLE IF NOT EXISTS `Company Offered Benefits` (
  `comp_offered_bene_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `benefit_id` INT NOT NULL,
  PRIMARY KEY (`comp_offered_bene_id`, `company_id`, `benefit_id`),
  INDEX `COMPANY_THAT_OFFERS_BENEFITS_FK_idx` (`company_id` ASC) VISIBLE,
  INDEX `BENEFITS_THAT_CAN_BE_OFFERED_FK_idx` (`benefit_id` ASC) VISIBLE,
  CONSTRAINT `COMPANY_THAT_OFFERS_BENEFITS_PK_FK`
    FOREIGN KEY (`company_id`)
    REFERENCES `Company` (`company_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `BENEFITS_THAT_CAN_BE_OFFERED_PK_FK`
    FOREIGN KEY (`benefit_id`)
    REFERENCES `Benefit` (`benefit_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Region` ;

CREATE TABLE IF NOT EXISTS `Region` (
  `region_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`region_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Company Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Company Region` ;

CREATE TABLE IF NOT EXISTS `Company Region` (
  `comp_region_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`comp_region_id`, `company_id`, `region_id`),
  INDEX `COMPANY_IN_A_REGION_FK_idx` (`company_id` ASC) VISIBLE,
  INDEX `REGION_THAT_HAS_COMPANY_FK_idx` (`region_id` ASC) VISIBLE,
  CONSTRAINT `COMPANY_IN_A_REGION_PK_FK`
    FOREIGN KEY (`company_id`)
    REFERENCES `Company` (`company_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `REGION_THAT_HAS_COMPANY_PK_FK`
    FOREIGN KEY (`region_id`)
    REFERENCES `Region` (`region_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payroll Compliance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payroll Compliance` ;

CREATE TABLE IF NOT EXISTS `Payroll Compliance` (
  `payroll_compliance_id` INT NOT NULL AUTO_INCREMENT,
  `region_id` INT NOT NULL,
  `type` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1024) NULL,
  `implementation_date` DATE NOT NULL,
  PRIMARY KEY (`payroll_compliance_id`),
  INDEX `REGION_WITH_COMPLIANCE_REQUIREMENTS_FK_idx` (`region_id` ASC) VISIBLE,
  CONSTRAINT `REGION_WITH_COMPLIANCE_REQUIREMENTS_FK`
    FOREIGN KEY (`region_id`)
    REFERENCES `Region` (`region_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Company Compliances`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Company Compliances` ;

CREATE TABLE IF NOT EXISTS `Company Compliances` (
  `comp_compliances_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `payroll_compliance_id` INT NOT NULL,
  PRIMARY KEY (`comp_compliances_id`, `company_id`, `payroll_compliance_id`),
  INDEX `COMPANY_FOLLOWING_COMPLIANCES_FK_idx` (`company_id` ASC) VISIBLE,
  INDEX `COMPLIANCES_FOR_COMPANIES_FK_idx` (`payroll_compliance_id` ASC) VISIBLE,
  CONSTRAINT `COMPANY_FOLLOWING_COMPLIANCES_PK_FK`
    FOREIGN KEY (`company_id`)
    REFERENCES `Company` (`company_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `COMPLIANCES_FOR_COMPANIES_PK_FK`
    FOREIGN KEY (`payroll_compliance_id`)
    REFERENCES `Payroll Compliance` (`payroll_compliance_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Job Title`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Job Title` ;

CREATE TABLE IF NOT EXISTS `Job Title` (
  `job_title_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(2048) NULL,
  PRIMARY KEY (`job_title_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee Job Titles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee Job Titles` ;

CREATE TABLE IF NOT EXISTS `Employee Job Titles` (
  `emp_job_titles_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `job_title_id` INT NOT NULL,
  PRIMARY KEY (`emp_job_titles_id`, `employee_id`, `job_title_id`),
  INDEX `EMPLOYEE_WITH_JOB_TITLE_FK_idx` (`employee_id` ASC) VISIBLE,
  INDEX `JOB_TITLE_CHOSEN_FK_idx` (`job_title_id` ASC) VISIBLE,
  CONSTRAINT `EMPLOYEE_WITH_JOB_TITLE_PK_FK`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `JOB_TITLE_CHOSEN_PK_FK`
    FOREIGN KEY (`job_title_id`)
    REFERENCES `Job Title` (`job_title_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee Benefits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee Benefits` ;

CREATE TABLE IF NOT EXISTS `Employee Benefits` (
  `emp_bene_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `benefit_id` INT NOT NULL,
  PRIMARY KEY (`emp_bene_id`, `employee_id`, `benefit_id`),
  INDEX `EMPLOYEE_WITH_BENEFITS_idx` (`employee_id` ASC) VISIBLE,
  INDEX `BENEFITS_CHOSEN_FK_idx` (`benefit_id` ASC) VISIBLE,
  CONSTRAINT `EMPLOYEE_WITH_BENEFITS_PK_FK`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `BENEFITS_CHOSEN_PK_FK`
    FOREIGN KEY (`benefit_id`)
    REFERENCES `Benefit` (`benefit_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Standard Deduction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Standard Deduction` ;

CREATE TABLE IF NOT EXISTS `Standard Deduction` (
  `standard_deduction_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(100) NOT NULL,
  `description` VARCHAR(4096) NULL,
  `cost` DECIMAL(65,2) NOT NULL,
  PRIMARY KEY (`standard_deduction_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee Standard Deductions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee Standard Deductions` ;

CREATE TABLE IF NOT EXISTS `Employee Standard Deductions` (
  `emp_stand_deduct_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `standard_deduction_id` INT NOT NULL,
  PRIMARY KEY (`emp_stand_deduct_id`, `employee_id`, `standard_deduction_id`),
  INDEX `EMPLOYEE_WITH_STANDARD_DEDUCTION_idx` (`employee_id` ASC) VISIBLE,
  INDEX `STANDARD_DEDUCTION_GIVEN_idx` (`standard_deduction_id` ASC) VISIBLE,
  CONSTRAINT `EMPLOYEE_WITH_STANDARD_DEDUCTION_PK_FK`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `STANDARD_DEDUCTION_GIVEN_PK_FK`
    FOREIGN KEY (`standard_deduction_id`)
    REFERENCES `Standard Deduction` (`standard_deduction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Previous Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Previous Employee` ;

CREATE TABLE IF NOT EXISTS `Previous Employee` (
  `pre_emp_id` INT NOT NULL AUTO_INCREMENT,
  `ssn` CHAR(9) NOT NULL,
  `leave_date` DATE NOT NULL,
  `exit_description` VARCHAR(4096) NULL,
  PRIMARY KEY (`pre_emp_id`, `ssn`),
  CONSTRAINT `PREVIOUS_EMPLOYEE_PERSON_PK_FK`
    FOREIGN KEY (`ssn`)
    REFERENCES `Person` (`ssn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Manager` ;

CREATE TABLE IF NOT EXISTS `Manager` (
  `manager_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `man_start_date` DATE NOT NULL,
  `man_role` VARCHAR(100) NULL,
  PRIMARY KEY (`manager_id`, `employee_id`),
  INDEX `MANAGER_EMPLOYEE_FK_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `MANAGER_EMPLOYEE_PK_FK`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Department` ;

CREATE TABLE IF NOT EXISTS `Department` (
  `depart_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(2048) NULL,
  PRIMARY KEY (`depart_id`),
  INDEX `COMPANY_WITH_DEPARTMENT_FK_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `COMPANY_WITH_DEPARTMENT_FK`
    FOREIGN KEY (`company_id`)
    REFERENCES `Company` (`company_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Managing in Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Managing in Departments` ;

CREATE TABLE IF NOT EXISTS `Managing in Departments` (
  `man_in_depart_id` INT NOT NULL AUTO_INCREMENT,
  `manager_id` INT NOT NULL,
  `depart_id` INT NOT NULL,
  PRIMARY KEY (`man_in_depart_id`, `manager_id`, `depart_id`),
  INDEX `MANAGER_AT_DEPARTMENT_FK_idx` (`manager_id` ASC) VISIBLE,
  INDEX `DEPARTMENT_BEING_MANAGED_FK_idx` (`depart_id` ASC) VISIBLE,
  CONSTRAINT `MANAGER_AT_DEPARTMENT_PK_FK`
    FOREIGN KEY (`manager_id`)
    REFERENCES `Manager` (`manager_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `DEPARTMENT_BEING_MANAGED_PK_FK`
    FOREIGN KEY (`depart_id`)
    REFERENCES `Department` (`depart_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employees in Departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employees in Departments` ;

CREATE TABLE IF NOT EXISTS `Employees in Departments` (
  `emp_in_depart_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `depart_id` INT NOT NULL,
  PRIMARY KEY (`emp_in_depart_id`, `employee_id`, `depart_id`),
  INDEX `DEPARTMENT_WITH_EMPLOYEES_FK_idx` (`employee_id` ASC) VISIBLE,
  INDEX `DEPARTMENT_WITH_EMPLOYEE_FK_idx` (`depart_id` ASC) VISIBLE,
  CONSTRAINT `EMPLOYEE IN DEPARTMENT_PK_FK`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `DEPARTMENT_WITH_EMPLOYEE_PK_FK`
    FOREIGN KEY (`depart_id`)
    REFERENCES `Department` (`depart_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Address` ;

CREATE TABLE IF NOT EXISTS `Address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `ssn` CHAR(9) NOT NULL,
  `street_address` VARCHAR(100) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` CHAR(2) NOT NULL,
  `zip_code` CHAR(5) NOT NULL,
  PRIMARY KEY (`address_id`),
  CONSTRAINT `PERSON_WITH_ADDRESS_FK`
    FOREIGN KEY (`ssn`)
    REFERENCES `Person` (`ssn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Phone Number`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Phone Number` ;

CREATE TABLE IF NOT EXISTS `Phone Number` (
  `phone_number_id` INT NOT NULL AUTO_INCREMENT,
  `ssn` CHAR(9) NOT NULL,
  `country_code` VARCHAR(5) NOT NULL,
  `area_code` CHAR(3) NOT NULL,
  `telephone_number` CHAR(7) NOT NULL,
  PRIMARY KEY (`phone_number_id`),
  UNIQUE INDEX `snn_UNIQUE` (`ssn` ASC) VISIBLE,
  CONSTRAINT `PERSON_PHONE_NUMBER_FK`
    FOREIGN KEY (`ssn`)
    REFERENCES `Person` (`ssn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Regional Standard Deductions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Regional Standard Deductions` ;

CREATE TABLE IF NOT EXISTS `Regional Standard Deductions` (
  `reg_stand_deduct_id` INT NOT NULL AUTO_INCREMENT,
  `standard_deduction_id` INT NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`reg_stand_deduct_id`, `standard_deduction_id`, `region_id`),
  INDEX `STANDARD_DEDUCTIONS_IN_REGION_FK_idx` (`standard_deduction_id` ASC) VISIBLE,
  INDEX `REGION_WITH_STANDARD_DEDUCTION_FK_idx` (`region_id` ASC) VISIBLE,
  CONSTRAINT `STANDARD_DEDUCTIONS_IN_REGION_PK_FK`
    FOREIGN KEY (`standard_deduction_id`)
    REFERENCES `Standard Deduction` (`standard_deduction_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `REGION_WITH_STANDARD_DEDUCTION_PK_FK`
    FOREIGN KEY (`region_id`)
    REFERENCES `Region` (`region_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Time Worked`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Time Worked` ;

CREATE TABLE IF NOT EXISTS `Time Worked` (
  `time_worked_id` INT NOT NULL AUTO_INCREMENT,
  `ssn` CHAR(9) NOT NULL,
  `company_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  PRIMARY KEY (`time_worked_id`),
  UNIQUE INDEX `ssn_UNIQUE` (`ssn` ASC) VISIBLE,
  INDEX `COMPANY_WHERE_TIME_WAS_WORKED_FK_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `PERSON_HAS_TIME_WORKED_FK`
    FOREIGN KEY (`ssn`)
    REFERENCES `Person` (`ssn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `COMPANY_WHERE_TIME_WAS_WORKED_FK`
    FOREIGN KEY (`company_id`)
    REFERENCES `Company` (`company_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hourly Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Hourly Employee` ;

CREATE TABLE IF NOT EXISTS `Hourly Employee` (
  `hourly_emp_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `hourly_wage` DECIMAL(65,2) NOT NULL,
  `wage_last_changed` DATE NOT NULL,
  PRIMARY KEY (`hourly_emp_id`, `employee_id`),
  INDEX `EMPLOYEE_PAID_HOURLY_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `EMPLOYEE_PAID_HOURLY_PK_FK`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Salary Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Salary Employee` ;

CREATE TABLE IF NOT EXISTS `Salary Employee` (
  `salary_emp_id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `salary_pay` DECIMAL(65,2) NOT NULL,
  `salary_last_changed` DATE NOT NULL,
  PRIMARY KEY (`salary_emp_id`, `employee_id`),
  INDEX `EMPLOYEE_PAID_SALARY_FK_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `EMPLOYEE_PAID_SALARY_PK_FK`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee Pay`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee Pay` ;

CREATE TABLE IF NOT EXISTS `Employee Pay` (
  `emp_pay_id` INT NOT NULL AUTO_INCREMENT,
  `ssn` CHAR(9) NOT NULL,
  `company_id` INT NOT NULL,
  `amount` DECIMAL(65,2) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`emp_pay_id`),
  INDEX `PERSON_PAID_AS_EMPLOYEE_FK_idx` (`ssn` ASC) VISIBLE,
  INDEX `COMPANY_THAT_PAID_EMPLOYEE_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `PERSON_PAID_AS_EMPLOYEE_FK`
    FOREIGN KEY (`ssn`)
    REFERENCES `Person` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `COMPANY_THAT_PAID_EMPLOYEE_FK`
    FOREIGN KEY (`company_id`)
    REFERENCES `Company` (`company_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payroll Payment Methods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payroll Payment Methods` ;

CREATE TABLE IF NOT EXISTS `Payroll Payment Methods` (
  `payroll_pay_methods_id` INT NOT NULL AUTO_INCREMENT,
  `employee_pay_id` INT NOT NULL,
  `pay_method_id` INT NOT NULL,
  PRIMARY KEY (`payroll_pay_methods_id`, `employee_pay_id`, `pay_method_id`),
  INDEX `EMPLOYEE_PAYMENT_METHOD_FK_idx` (`employee_pay_id` ASC) VISIBLE,
  INDEX `PAYMENT_METHOD_FOR_EMPLOYEE_PAY_FK_idx` (`pay_method_id` ASC) VISIBLE,
  CONSTRAINT `EMPLOYEE_PAY_PAYMENT_METHOD_PK_FK`
    FOREIGN KEY (`employee_pay_id`)
    REFERENCES `Employee Pay` (`emp_pay_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `PAYMENT_METHOD_FOR_EMPLOYEE_PAY_PK_FK`
    FOREIGN KEY (`pay_method_id`)
    REFERENCES `Payment Method` (`pay_method_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Check`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Check` ;

CREATE TABLE IF NOT EXISTS `Check` (
  `check_id` INT NOT NULL AUTO_INCREMENT,
  `pay_method_id` INT NOT NULL,
  `check_number` VARCHAR(10) NOT NULL,
  `bank_name` VARCHAR(45) NOT NULL,
  `signed_by` VARCHAR(45) NOT NULL,
  `account_number` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`check_id`, `pay_method_id`),
  INDEX `PAYMENT_METHOD_CHECK_FK_idx` (`pay_method_id` ASC) VISIBLE,
  CONSTRAINT `PAYMENT_METHOD_CHECK_PK_FK`
    FOREIGN KEY (`pay_method_id`)
    REFERENCES `Payment Method` (`pay_method_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Direct Deposit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Direct Deposit` ;

CREATE TABLE IF NOT EXISTS `Direct Deposit` (
  `direct_deposit_id` INT NOT NULL AUTO_INCREMENT,
  `pay_method_id` INT NOT NULL,
  `bank_name` VARCHAR(45) NOT NULL,
  `account_number` VARCHAR(12) NOT NULL,
  `routing_number` CHAR(9) NOT NULL,
  PRIMARY KEY (`direct_deposit_id`, `pay_method_id`),
  INDEX `PAYMENT_METHOD_DIRECT_DEPOSIT_FK_idx` (`pay_method_id` ASC) VISIBLE,
  CONSTRAINT `PAYMENT_METHOD_DIRECT_DEPOSIT_PK_FK`
    FOREIGN KEY (`pay_method_id`)
    REFERENCES `Payment Method` (`pay_method_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `History`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `History` ;

CREATE TABLE IF NOT EXISTS `History` (
  `hist_id` INT NOT NULL AUTO_INCREMENT,
  `ssn` CHAR(9) NOT NULL,
  `company_id` INT NOT NULL,
  `isa_type` VARCHAR(45) NOT NULL,
  `starting_date` DATE NOT NULL,
  `ending_date` DATE NOT NULL,
  PRIMARY KEY (`hist_id`),
  INDEX `PERSONS_HISTORY_FK_idx` (`ssn` ASC) VISIBLE,
  INDEX `COMPANYS_HISTORY_WITH_PERSON_FK_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `PERSONS_HISTORY_AT_COMPANY_FK`
    FOREIGN KEY (`ssn`)
    REFERENCES `Person` (`ssn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `COMPANYS_HISTORY_WITH_PERSON_FK`
    FOREIGN KEY (`company_id`)
    REFERENCES `Company` (`company_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wage History`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Wage History` ;

CREATE TABLE IF NOT EXISTS `Wage History` (
  `wage_hist_id` INT NOT NULL AUTO_INCREMENT,
  `hist_id` INT NOT NULL,
  `type_of_wage` VARCHAR(100) NOT NULL,
  `wage_amount` DECIMAL(65,2) NOT NULL,
  PRIMARY KEY (`wage_hist_id`, `hist_id`),
  INDEX `HISTORY_OF_WAGES_FK_idx` (`hist_id` ASC) VISIBLE,
  CONSTRAINT `HISTORY_OF_WAGES_PK_FK`
    FOREIGN KEY (`hist_id`)
    REFERENCES `History` (`hist_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Benefit History`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Benefit History` ;

CREATE TABLE IF NOT EXISTS `Benefit History` (
  `benefit_hist_id` INT NOT NULL AUTO_INCREMENT,
  `hist_id` INT NOT NULL,
  `type_of_benefit` VARCHAR(100) NOT NULL,
  `benefit_description` VARCHAR(4096) NULL,
  `deduction_amount` DECIMAL(65,2) NOT NULL,
  PRIMARY KEY (`benefit_hist_id`, `hist_id`),
  INDEX `HISTORY_OF_BENEFITS_FK_idx` (`hist_id` ASC) VISIBLE,
  CONSTRAINT `HISTORY_OF_BENEFITS_PK_FK`
    FOREIGN KEY (`hist_id`)
    REFERENCES `History` (`hist_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Used Paid Time Off`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Used Paid Time Off` ;

CREATE TABLE IF NOT EXISTS `Used Paid Time Off` (
  `paid_time_off_id` INT NOT NULL AUTO_INCREMENT,
  `ssn` CHAR(9) NOT NULL,
  `company_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `description` VARCHAR(4096) NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`paid_time_off_id`),
  INDEX `PERSONS_USED_PAID_TIME_OFF_FK_idx` (`ssn` ASC) VISIBLE,
  INDEX `COMPANY_GIVEN_PAID_TIME_OFF_FK_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `PERSONS_USED_PAID_TIME_OFF_FK`
    FOREIGN KEY (`ssn`)
    REFERENCES `Person` (`ssn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `COMPANY_GIVEN_PAID_TIME_OFF_FK`
    FOREIGN KEY (`company_id`)
    REFERENCES `Company` (`company_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Company Tax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Company Tax` ;

CREATE TABLE IF NOT EXISTS `Company Tax` (
  `company_tax_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `region_id` INT NULL,
  `type` VARCHAR(100) NOT NULL,
  `description` VARCHAR(4096) NULL,
  `due_date` DATE NOT NULL,
  `dollar_amount` DECIMAL(65,2) NOT NULL,
  `paid` TINYINT NOT NULL,
  PRIMARY KEY (`company_tax_id`),
  INDEX `COMPANY_PAYING_TAX_FK_idx` (`company_id` ASC) VISIBLE,
  INDEX `REGION_TAXING_COMPANY_FK_idx` (`region_id` ASC) VISIBLE,
  CONSTRAINT `COMPANY_PAYING_TAX_FK`
    FOREIGN KEY (`company_id`)
    REFERENCES `Company` (`company_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `REGION_TAXING_COMPANY_FK`
    FOREIGN KEY (`region_id`)
    REFERENCES `Region` (`region_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employee Tax Document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employee Tax Document` ;

CREATE TABLE IF NOT EXISTS `Employee Tax Document` (
  `emp_tax_doc_id` INT NOT NULL AUTO_INCREMENT,
  `ssn` CHAR(9) NOT NULL,
  `company_id` INT NOT NULL,
  `form_type` VARCHAR(45) NULL,
  `description` VARCHAR(1024) NULL,
  `date_distributed` DATE NOT NULL,
  PRIMARY KEY (`emp_tax_doc_id`),
  INDEX `PERSON_WITH_TAX_DOCUMENT_FK_idx` (`ssn` ASC) VISIBLE,
  INDEX `COMPANY_ISSUING_TAX_DOCUMENT_FK_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `PERSON_WITH_TAX_DOCUMENT_FK`
    FOREIGN KEY (`ssn`)
    REFERENCES `Person` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `COMPANY_ISSUING_TAX_DOCUMENT_FK`
    FOREIGN KEY (`company_id`)
    REFERENCES `Company` (`company_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Email Support`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Email Support` ;

CREATE TABLE IF NOT EXISTS `Email Support` (
  `email_supp_id` INT NOT NULL AUTO_INCREMENT,
  `topic` VARCHAR(255) NOT NULL,
  `department` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`email_supp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Email Support Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Email Support Request` ;

CREATE TABLE IF NOT EXISTS `Email Support Request` (
  `email_supp_req_id` INT NOT NULL AUTO_INCREMENT,
  `email_supp_id` INT NULL,
  `user_id` INT NULL,
  `subject` VARCHAR(100) NOT NULL,
  `content` VARCHAR(4096) NOT NULL,
  `contact` VARCHAR(45) NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`email_supp_req_id`),
  INDEX `EMAIL_SUPPORT_REQUESTED_FK_idx` (`email_supp_id` ASC) VISIBLE,
  INDEX `USER_REQUESTING_EMAIL_SUPPORT_FK_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `EMAIL_SUPPORT_REQUESTED_FK`
    FOREIGN KEY (`email_supp_id`)
    REFERENCES `Email Support` (`email_supp_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `USER_REQUESTING_EMAIL_SUPPORT_FK`
    FOREIGN KEY (`user_id`)
    REFERENCES `User` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Live Chat Support`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Live Chat Support` ;

CREATE TABLE IF NOT EXISTS `Live Chat Support` (
  `live_chat_supp_id` INT NOT NULL AUTO_INCREMENT,
  `topic` VARCHAR(255) NOT NULL,
  `department` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`live_chat_supp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Live Chat Support Request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Live Chat Support Request` ;

CREATE TABLE IF NOT EXISTS `Live Chat Support Request` (
  `live_chat_supp_req_id` INT NOT NULL AUTO_INCREMENT,
  `live_chat_supp_id` INT NULL,
  `user_id` INT NULL,
  `subject` VARCHAR(100) NOT NULL,
  `date` DATE NOT NULL,
  `start_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `agent` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`live_chat_supp_req_id`),
  INDEX `LIVE_CHAT_SUPPORT_REQUESTED_FK_idx` (`live_chat_supp_id` ASC) VISIBLE,
  INDEX `USER_REQUESTING_LIVE_CHAT_SUPPORT_FK_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `LIVE_CHAT_SUPPORT_REQUESTED_FK`
    FOREIGN KEY (`live_chat_supp_id`)
    REFERENCES `Live Chat Support` (`live_chat_supp_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `USER_REQUESTING_LIVE_CHAT_SUPPORT_FK`
    FOREIGN KEY (`user_id`)
    REFERENCES `User` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Report Option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Report Option` ;

CREATE TABLE IF NOT EXISTS `Report Option` (
  `report_option_id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  `design` VARCHAR(100) NOT NULL,
  `color_scheme` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`report_option_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Report` ;

CREATE TABLE IF NOT EXISTS `Report` (
  `report_id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `report_option_id` INT NULL,
  `title` VARCHAR(255) NOT NULL,
  `author` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1024) NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`report_id`),
  INDEX `COMPANY_REPORT_FK_idx` (`company_id` ASC) VISIBLE,
  INDEX `REPORT_CHOSEN_OPTIONS_FK_idx` (`report_option_id` ASC) VISIBLE,
  CONSTRAINT `COMPANY_REPORT_FK`
    FOREIGN KEY (`company_id`)
    REFERENCES `Company` (`company_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `REPORT_CHOSEN_OPTIONS_FK`
    FOREIGN KEY (`report_option_id`)
    REFERENCES `Report Option` (`report_option_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
